sxxp/apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),  # 购物车记录添加
    url(r'^$', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
]

sxxp/apps/goods/urls.py
from django.conf.urls import url
from apps.goods.views import IndexView, DetailView, ListView, ActionView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 列表页
    url(r'^action/(?P<index>\d+)$', ActionView.as_view(), name='action'), # 首页促销活动页面
    url(r'^$', IndexView.as_view(), name='index'),  # 首页  对应什么都不输入的情况，但是乱输则访问不了
]

sxxp/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, AddressView, LogoutView


urlpatterns = [
    # url(r'^register$', views.register, name='register'),
    # url(r'^register_handle$', views.register_handle, name='register_hanle')

    url(r'^register$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    url(r'^login$', LoginView.as_view(), name='login'),  # 登录
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 注销登录

    # url(r'^$', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # url(r'^order$', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # url(r'^address$', login_required(AddressView.as_view()), name='address'),  # 用户中心-地址页

    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    # url(r'^order$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'), # 用户中心-订单页
    url(r'^address$', AddressView.as_view(), name='address'),  # 用户中心-地址页
]

sxxp/dailyfresh/urls.py
from django.conf.urls import url,include
from django.urls import path
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search', include('haystack.urls')), # 全文检索框架
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('order.urls', 'order'), namespace='order')),
    url(r'^', include(('goods.urls', 'goods'), namespace='goods')), # 用户啥也不输入则最后匹配到商品模块
]

sxxp/apps/cart/models.py
from django.db import models

# Create your models here.

sxxp/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse

from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
# Create your views here.

# 添加商品到购物车:
# 1）请求方式，采用ajax post
# 如果涉及到数据的修改(新增，更新，删除), 采用post
# 如果只涉及到数据的获取，采用get
# 2) 传递参数: 商品id(sku_id) 商品数量(count)


# ajax发起的请求都在后台，在浏览器中看不到效果
# /cart/add
class CartAddView(View):
    '''购物车记录添加'''
    def post(self, request):
        '''购物车记录添加'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res':0, 'errmsg':'请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res':1, 'errmsg':'数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res':2, 'errmsg':'商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res':3, 'errmsg':'商品不存在'})

        # 业务处理:添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget cart_key 属性
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4, 'errmsg':'商品库存不足'})

        # 设置hash中sku_id对应的值
        # hset->如果sku_id已经存在，更新数据， 如果sku_id不存在，添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res':5, 'total_count':total_count, 'message':'添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面显示'''
    def get(self, request):
        '''显示'''
        # 获取登录的用户
        user = request.user
        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # {'商品id':商品数量}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 动态给sku对象增加一个属性amount, 保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count, 保存购物车中对应商品的数量
            sku.count = int(count)
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {'total_count':total_count,
                   'total_price':total_price,
                   'skus':skus}

        # 使用模板
        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品id(sku_id) 更新的商品数量(count)
# /cart/update
class CartUpdateView(View):
    '''购物车记录更新'''
    def post(self, request):
        '''购物车记录更新'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理:更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4, 'errmsg':'商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':5, 'total_count':total_count, 'message':'更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品的id(sku_id)
# /cart/delete
class CartDeleteView(View):
    '''购物车记录删除'''
    def post(self, request):
        '''购物车记录删除'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'res':1, 'errmsg':'无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res':2, 'errmsg':'商品不存在'})

        # 业务处理:删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':3, 'total_count':total_count, 'message':'删除成功'})

sxxp/templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到生鲜小铺!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/xiaologo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">服务条款</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>-----&nbsp;&nbsp;&nbsp;&nbsp;2022&nbsp;&nbsp;南昌理工学院&nbsp;&nbsp;生鲜小铺&nbsp;&nbsp;&nbsp;&nbsp;-----</p>
		<p>电话：133****025&nbsp;&nbsp;邮箱：211***097@qq.com</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

sxxp/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网站主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

sxxp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}生鲜小铺-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>

		<div class="slide fl">
			<ul class="slide_pics">
				{% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>
    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				    {% endfor %}
                </div>
                <a href="{% url 'goods:list' type_id=type.id page=1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for banner in type.image_banners %}
                    <li>
                        <h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">¥ {{ banner.sku.price }}</div>
                    </li>
				    {% endfor %}
                </ul>
            </div>
	    </div>
    {% endfor %}



{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model02">海鲜水产</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">河虾</a>#}
{#				<a href="#">扇贝</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="images/banner02.jpg"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">青岛野生海捕大青虾</a></h4>#}
{#					<a href="#"><img src="images/goods/goods018.jpg"></a>#}
{#					<div class="prize">¥ 48.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">扇贝</a></h4>#}
{#					<a href="#"><img src="images/goods/goods019.jpg"></a>#}
{#					<div class="prize">¥ 46.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">冷冻秋刀鱼</a></h4>#}
{#					<a href="#"><img src="images/goods/goods020.jpg"></a>#}
{#					<div class="prize">¥ 19.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">基围虾</a></h4>#}
{#					<a href="#"><img src="images/goods/goods021.jpg"></a>#}
{#					<div class="prize">¥ 25.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model03">猪牛羊肉</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="images/banner03.jpg"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model04">禽类蛋品</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="images/banner04.jpg"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model05">新鲜蔬菜</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="images/banner05.jpg"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model06">速冻食品</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="images/banner06.jpg"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">维多利亚葡萄</a></h4>#}
{#					<a href="#"><img src="images/goods.jpg"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}

{% endblock %}

sxxp/templates/static_base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>